version: '3.9'
services:
  mysql:
    image: mysql:8.0.36
    env_file: ./env/mysql.env
    volumes:
      - mysql_data_container:/data/db
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
      interval: 5s
      timeout: 3s
      retries: 5
  app-1: &app
    image: josemateus1998/dummy:latest
    env_file: ./env/app.env
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - '8080:8080'
  app-2:
    <<: *app
  nginx:
    image: nginx:stable-alpine
    ports:
      - '80:80'
    volumes:
      - ./nginx:/etc/nginx/conf.d
    restart: unless-stopped
    depends_on:
      - app-1
      - app-2
  redis:
    image: redis:7.2.4
    ports:
      - '6379:6379'
    restart: unless-stopped
    depends_on:
      - app-1
      - app-2
volumes:
  mysql_data_container: